export interface Painting {
  accessionmethod: string
  accessionyear: number
  accesslevel: number
  century: string
  classification: string
  classificationid: number
  colorcount: number
  commentary: any
  contact: string
  contextualtextcount: number
  copyright: string
  creditline: string
  culture: string
  datebegin: number
  dated: string
  dateend: number
  dateoffirstpageview: string
  dateoflastpageview: string
  department: string
  description: any
  dimensions:string
  division: string
  edition: any
  exhibitioncount: number
  groupcount: number
  id: number
  imagecount: number
  imagepermissionlevel: number
  images: any[]
  labeltext: any
  lastupdate: string
  lendingpermissionlevel: number
  markscount: number
  mediacount: number
  medium: any
  objectid:number
  objectnumber: string
  people: any[]
  peoplecount: number
  period: any
  periodid: any
  primaryimageurl: any
  provenance: string
  publicationcount: number
  rank: number
  relatedcount: number
  seeAlso: any[]
  signed: any
  standardreferencenumber: any
  state: any
  style: any
  technique: string
  techniqueid: number
  title: string
  titlescount: number
  totalpageviews: number
  totaluniquepageviews: number
  url: string
  verificationlevel: number
  verificationleveldescription: string
  worktypes: any[]
  }
